theme: jekyll-theme-minimal
title: SFU Locomotion Lab

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/combine_lab_logo.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Software: "software"
  About the lab: "aboutus"
  Prospective members: "joining"
  #Author's home: "http://deanattali.com"
